name: xz
desc: XZ Utils is free general-purpose data compression software 
ver: 5.2.5
srcs: [ http://tukaani.org/xz/xz-{{ .ver }}.tar.gz ]
subpkgs: [ {{ .name }}-dev ]
entries:
  - type: autotools
    folder: {{ .name }}-{{ .ver }}
    cfgopts: [ disable-static ]
