{{ $version := "1.2.2" }}
name: libc
description: Standart C library
version: {{ $version }}
subpackages:
  - dev
sources:
  - http://musl.libc.org/releases/musl-{{ $version }}.tar.gz
build:
  - type: custom
    folder: musl-{{ $version }}
    build: |
      ../configure
        --prefix=/usr \
        --libdir=/lib \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --disable-eh-frame
      make
    install: |
      make DESTDIR="$pkgdir" install
