{{ $version := "1.2.2" }}
name: libc
description: Standart C library
version: {{ $version }}
subpackages:
  - dev
sources:
  - http://musl.libc.org/releases/musl-{{ $version }}.tar.gz
build:
  - type: autotools
    folder: musl-{{ $version }}
