name: libc
desc: Standart C library
ver: 2.34
makedeps: [ linux-api-headers ]
subpkgs: [ {{ .name }}-dev ]
srcs: [ "https://ftp.gnu.org/gnu/glibc/glibc-{{ .ver }}.tar.gz" ]
entries:
  - type: autotools
    folder: glibc-{{ .ver }}
    env: 
      - CC="gcc -ffile-prefix-map=/tools=/usr"
      - CXX="g++ -ffile-prefix-map=/tools=/usr"
      - LD="ld"
    cfgopts:
      - disable-werror
      - enable-kernel="3.2"
      - enable-stack-protector=strong
      - with-headers=/usr/include libc_cv_slibdir=/lib
    after: |
      cp ../nscd/nscd.conf "$pkgdir/etc/nscd.conf"
      mkdir -p "$pkgdir/var/cache/nscd"
      make localedata/install-locales DESTDIR="$pkgdir"
