{{ $version := "1.2.11" }}
name: libz
description: A Massively Spiffy Yet Delicately Unobtrusive Compression Library
version: {{ $version }}
sources:
  - http://zlib.net/zlib-{{ $version }}.tar.gz
build:
  - type: autotools
    no_triplet: y
    folder: zlib-{{ $version }}
subpackages:
  - type: integrated
    name: dev
