name: libz
desc: A Massively Spiffy Yet Delicately Unobtrusive Compression Library
ver: 1.2.11
subpkgs: [ {{ .name }}-dev ]
srcs: [ http://zlib.net/zlib-{{ .ver }}.tar.gz ]
entries:
  - type: autotools
    folder: zlib-{{ .ver }}
    cfgopts: [ shared ]
