name: binutils
desc: The GNU Binutils are a collection of binary tools
ver: "2.37"
deps: [ libz ]
subpkgs: [ {{ .name }}-dev ]
makedeps: [ libz-dev ]
srcs: [ http://ftp.gnu.org/gnu/binutils/binutils-{{ .ver }}.tar.gz ]
entries:
  - type: autotools
    folder: {{ .name }}-{{ .ver }}
    cfgopts:
      - enable-gold
      - enable-ld=default
      - enable-plugins
      - enable-shared
      - enable-64-bit-bfd
      - with-system-zlib
    installopts:
      - tooldir=/usr
