name: pfetch
desc: A pretty system information tool written in POSIX sh
ver: 0.6.0
srcs: [ pfetch-{{ .ver }}.tar.gz::http://github.com/dylanaraps/pfetch/archive/refs/tags/{{ .ver }}.tar.gz ]
deps: [ bash ]
entries:
  - type: custom
    folder: pfetch-{{ .ver }}
    build: |
      mkdir -p "$pkgdir/bin"
      mv pfetch "$pkgdir/bin/"
