{{ $version := "0.6.0" }}
name: pfetch
description: A pretty system information tool written in POSIX sh
version: {{ $version }}
sources:
  - pfetch-{{ $version }}.tar.gz::http://github.com/dylanaraps/pfetch/archive/refs/tags/{{ $version }}.tar.gz
build:
  - type: custom
    folder: pfetch-{{ $version }}
    install: |
      mkdir -p "$pkgdir/bin"
      mv pfetch "$pkgdir/bin/"
