name: pax-utils
desc: ELF related utils
ver: 1.3.3
srcs: [ http://gitweb.gentoo.org/proj/pax-utils.git/snapshot/pax-utils-{{ .ver }}.tar.gz ]
entries:
  - type: custom
    folder: {{ .name }}-{{ .ver }}
    build: |
      make
      mkdir -p "$pkgdir/bin"
      mv pspax scanelf dumpelf scanmacho "$pkgdir/bin/"
