name: tar
desc: GNU Tar provides the ability to create tar archives, as well as various other kinds of manipulation
ver: 1.34
srcs: [ http://ftp.gnu.org/gnu/tar/tar-{{ .ver }}.tar.gz ]
entries:
  - type: autotools
    folder: {{ .name }}-{{ .ver }}
    env: [ FORCE_UNSAFE_CONFIGURE=1 ]
    cfgopts: [ disable-static ]
