{{ $version := "1.34" }}
name: tar
description: GNU Tar provides the ability to create tar archives, as well as various other kinds of manipulation
version: {{ $version }}
sources:
  - http://ftp.gnu.org/gnu/tar/tar-{{ $version }}.tar.gz
build:
  - type: autotools
    folder: tar-{{ $version }}
    opts:
      - disable-static FORCE_UNSAFE_CONFIGURE=1
