name: bash
desc: Bash is the GNU Project's shell—the Bourne Again SHell
ver: 5.1
srcs: [ http://ftp.gnu.org/gnu/bash/bash-{{ .ver }}.tar.gz ]
subpkgs: [ {{ .name }}-dev ]
entries:
  - type: autotools
    folder: bash-{{ .ver }}
    env:
      - MAKEFLAGS="-j1"
    cfgopts: [ without-bash-malloc ]
    after: |
      cd "$pkgdir/bin"
      ln -s bash sh
      ln -s bash ash
